#+TITLE: Doom Emacs Configuration

* Reference

[[https://github.com/doomemacs/doomemacs/blob/master/docs/getting_started.org][doom - getting started]]

[[https://docs.doomemacs.org/latest/][Documentation - Doom Emacs latest documentation]]

My personal doom emacs configuration.

* Non-standard binds
** global map

| key     | command                     |
|---------+-----------------------------|
| ~v~ ~V~     | expand/contract region      |
| ~SPC s o~ | consult-outline             |
| ~SPC s f~ | consult-find                |
| ~SPC s y~ | consult-yank-from-kill-ring |
| SPC b o | consult-buffer-other-window |
| SPC r l | consult-register-load       |
| SPC r s | consult-register-store      |
| SPC r r | consult-register            |
| ~M-SPC~   | cycle-spacing               |
| ~SPC t m~ | style/max-frame             |
| ~SPC t d~ | style/default-frame         |
| ~gss~     | evil-avy-goto-char-timer    |
| ~gs/~     | evil-avy-goto-char-2        |
| ~C-r~     | isearch-backwards           |
| ~M-s-s~   | isearch-forward-regexp      |
| ~M-j~     | avy-isearch                 |
| M-n     | flycheck-next-error         |
| M-p     | flycheck-previous-error     |
|         |                             |

** org map

| ~SPC m l p~ | org-hugo-export-wim-to-md |
| ~SPC m z~   | yank into block commands  |
| SPC m j   | org-random-todo-goto-new  |
|           |                           |

** haskell-ng map

| SPC m n   | flymake-goto-next-error |
| SPC m p   | flymake-goto-prev-error |
| SPC m e   | consult-flymake         |
| SPC m '   | haskell-ng-repl-run     |
| SPC m = = | ormolu-format-buffer    |
| SPC m c a | eglot-code-actions      |
| SPC m , e | eglot                   |
| SPC m , l | lsp                     |
| SPC m , r | eglot-reconnect         |
| SPC m , q | eglot-shutdown          |
| SPC m = = | cabal-format-buffer     |
| SPC m = r | cabal-format-region     |
|           |                         |

* Configuration Examples

Most of my doom config, and much of my work flow has been put together from reading and stealing from other configs.

A useful technique is to do an advanced github search of these repos, together with the main doom-emacs repository. An example:

[[https://github.com/search?q=vertico+(repo%3Adoomemacs%2Fdoomemacs+OR+repo%3Ahlissner%2F.doom.d+OR+repo%3Afloscr%2Femacs.d+OR+repo%3ALemonBreezes%2Fcyber-angel-emacs+OR+repo%3Adangirsh%2F.doom.d+OR+repo%3Atecosaur%2Femacs-config+OR+repo%3Azzamboni%2Fdot-emacs+OR+repo%3AMatthewZMD%2F.emacs.d+OR+repo%3Akarthink%2F.emacs.d+OR+repo%3Aprotesilaos%2Fdotfiles+OR+repo%3Asachac%2F.emacs.d)&type=code&ref=advsearch][Example search on vertico]]

** doom'ish

[[https://github.com/LemonBreezes/cae-emacs][LemonBreezes]]

[[https://github.com/floscr/emacs.d][floscr]]

[[https://github.com/dangirsh/.doom.d][dangirsh]]

[[https://github.com/hlissner/doom-emacs-private][hlissner]]

[[https://github.com/tecosaur/emacs-config/][tecosaur]]

[[https://github.com/zzamboni/dot-doom/][zzamboni]]

** from-scratch'ish

[[https://github.com/sachac/.emacs.d][sachac]]

[[https://github.com/MatthewZMD/.emacs.d][MatthewZMD]]

[[https://github.com/karthink/.emacs.d][karthink]]

[[https://github.com/protesilaos/dotfiles][protesilaos]]

** haskell'ish

[[https://gitlab.com/magus/mes][magus]]

* Front Matter

As per default doom config.el.

[[https://elpa.gnu.org/packages/doc/modus-themes.html#Fringes][Modus themes for GNU Emacs]]
[[https://protesilaos.com/emacs/modus-themes][Modus Themes (Modus Operandi and Modus Vivendi) | Protesilaos Stavrou]]
[[https://protesilaos.com/emacs/ef-themes#h:ac76ded0-af9b-4566-aff9-75142ef2d4ef][Ef (εὖ) themes for GNU Emacs | Protesilaos Stavrou]]

#+begin_src elisp
;;; $DOOMDIR/config.el -*- lexical-binding: t; -*-

;; Place your private configuration here! Remember, you do not need to run 'doom
;; sync' after modifying this file!

;; other configuration examples
;;

;; Some functionality uses this to identify you, e.g. GPG configuration, email
;; clients, file templates and snippets.
(setq user-full-name "Tony Day"
      user-mail-address "tonyday567@gmail.com")

;; Doom exposes five (optional) variables for controlling fonts in Doom. Here
;; are the three important ones:
;;
;; + `doom-font'
;; + `doom-variable-pitch-font'
;; + `doom-big-font' -- used for `doom-big-font-mode'; use this for
;;   presentations or streaming.
;;
;; They all accept either a font-spec, font string ("Input Mono-12"), or xlfd
;; font string. You generally only need these two:
;;(setq doom-font (font-spec :family "Iosevka ss02" :size 14 :weight 'light)
;;      doom-variable-pitch-font (font-spec :family "Iosevka etoile" :size 14))
(setq doom-font (font-spec :family "Victor Mono")
      doom-variable-pitch-font (font-spec :family "Iosevka Aile"))

;;(setq doom-font (font-spec :family "Iosevka")
;;      doom-variable-pitch-font (font-spec :family "Iosevka Aile"))

;; There are two ways to load a theme. Both assume the theme is installed and
;; available. You can either set `doom-theme' or manually load a theme with the
;; `load-theme' function. This is the default:
;; (setq doom-theme 'doom-Iosvkem)
(setq doom-theme 'modus-vivendi)
;; (setq doom-theme 'ef-bio)
;; (doom-themes-org-config)

;; If you use `org' and don't want your org files in the default location below,
;; change `org-directory'. It must be set before org loads!
(setq org-directory "~/org/")

;; This determines the style of line numbers in effect. If set to `nil', line
;; numbers are disabled. For relative line numbers, set this to `relative'.
(setq display-line-numbers-type nil)

;; Here are some additional functions/macros that could help you configure Doom:
;;
;; - `load!' for loading external *.el files relative to this one
;; - `use-package!' for configuring packages
;; - `after!' for running code after a package has loaded
;; - `add-load-path!' for adding directories to the `load-path', relative to
;;   this file. Emacs searches the `load-path' when you load packages with
;;   `require' or `use-package'.
;; - `map!' for binding new keys
;;
;; To get information about any of these functions/macros, move the cursor over
;; the highlighted symbol at press 'K' (non-evil users must press 'C-c c k').
;; This will open documentation for it, including demos of how they are used.
;;
;; You can also try 'gd' (or 'C-c c d') to jump to their definition and see how
;; they are implemented.

#+end_src

* Doom

Global and standard doom library tweaks.

** globals

#+begin_src elisp
(setq evil-split-window-below t
      evil-vsplit-window-right t
      confirm-kill-emacs nil
      confirm-kill-processes nil
      shift-select-mode t
      window-combination-resize t
      case-fold-search t
      auto-save-default t)

;; setq-default sets variables that are usually local to buffers
(setq-default truncate-lines nil
              indent-tabs-mode nil)

(map! ;; removes from kill ring
      [remap backward-kill-word] #'doom/delete-backward-word
      ;; replaces just-one-space
      "M-SPC" #'cycle-spacing
      [remap ibuffer] #'ibuffer-jump)

#+end_src

** doom-modeline

#+begin_src elisp
(setq doom-modeline-lsp-icon nil)
(setq doom-modeline-buffer-encoding nil)
(setq doom-modeline-buffer-state-icon nil)
(setq doom-modeline-vcs-max-length 8)
(setq doom-modeline-lsp nil)
(setq doom-modeline-modal nil)
#+end_src

** default frame

#+begin_src elisp
(defun style/left-frame ()
  (interactive)
  (cond
   ((string-equal system-type "windows-nt") ; Microsoft Windows
    (progn
      (set-frame-parameter (selected-frame) 'fullscreen nil)
      (set-frame-parameter (selected-frame) 'vertical-scroll-bars nil)
      (set-frame-parameter (selected-frame) 'horizontal-scroll-bars nil)
      (set-frame-parameter (selected-frame) 'top 10)
      (set-frame-parameter (selected-frame) 'left 6)
      (set-frame-parameter (selected-frame) 'height 40)
      (set-frame-parameter (selected-frame) 'width 120)))
   ((string-equal system-type "darwin") ; Mac OS X
    (progn
      (set-frame-parameter (selected-frame) 'fullscreen nil)
      (set-frame-parameter (selected-frame) 'vertical-scroll-bars nil)
      (set-frame-parameter (selected-frame) 'horizontal-scroll-bars nil)
      (set-frame-parameter (selected-frame) 'top 23)
      (set-frame-parameter (selected-frame) 'left 0)
      (set-frame-parameter (selected-frame) 'height 44)
      (set-frame-parameter (selected-frame) 'width 100)
      (message "default-frame set")))
   ((string-equal system-type "gnu/linux") ; linux
    (progn
      (message "Linux")))))

(add-to-list 'initial-frame-alist '(top . 23))
(add-to-list 'initial-frame-alist '(left . 0))
(add-to-list 'initial-frame-alist '(height . 44))
(add-to-list 'initial-frame-alist '(width . 100))

(defun style/max-frame ()
  (interactive)
  (if t
      (progn
        (set-frame-parameter (selected-frame) 'fullscreen 'fullboth)
        (set-frame-parameter (selected-frame) 'vertical-scroll-bars nil)
        (set-frame-parameter (selected-frame) 'horizontal-scroll-bars nil))
    (set-frame-parameter (selected-frame) 'top 26)
    (set-frame-parameter (selected-frame) 'left 2)
    (set-frame-parameter (selected-frame) 'width
                         (floor (/ (float (x-display-pixel-width)) 9.15)))
    (if (= 1050 (x-display-pixel-height))
        (set-frame-parameter (selected-frame) 'height
                             (if (>= emacs-major-version 24)
                                 66
                               55))
      (set-frame-parameter (selected-frame) 'height
                           (if (>= emacs-major-version 24)
                               75
                             64)))))

(style/left-frame)  ;; Focus new window after splitting
(map!
   :leader
   :nvm "tm" #'style/max-frame
   :nvm "td" #'style/left-frame)
#+end_src

** evil

#+begin_src elisp
(map!
 (:map 'override
   :v "v" #'er/expand-region
   :v "V" #'er/contract-region))
(map!
 (:map 'override
   :m "j" #'evil-next-visual-line
   :m "k" #'evil-previous-visual-line))
#+end_src

#+begin_src elisp
(setq evil-kill-on-visual-paste nil
      evil-want-C-u-scroll nil
      evil-want-integration t
      evil-want-keybinding nil
      evil-move-cursor-back nil
      evil-move-beyond-eol t
      evil-highlight-closing-paren-at-point-states nil)
#+end_src

#+begin_src elisp
(defun evil-forward-after-end (thing &optional count)
  "Move forward to end of THING.
The motion is repeated COUNT times."
  (setq count (or count 1))
  (cond
   ((> count 0)
    (forward-thing thing count))
   (t
    (unless (bobp) (forward-char -1))
    (let ((bnd (bounds-of-thing-at-point thing))
          rest)
      (when bnd
        (cond
         ((< (point) (cdr bnd)) (goto-char (car bnd)))
         ((= (point) (cdr bnd)) (cl-incf count))))
      (condition-case nil
          (when (zerop
                 (setq rest
                       (forward-thing thing count)))
            (end-of-thing thing))
        (error))
      rest))))

(evil-define-motion evil-forward-after-word-end (count &optional bigword)
  "Move the cursor to the end of the COUNT-th next word.
If BIGWORD is non-nil, move by WORDS."
  :type inclusive
  (let ((thing (if bigword 'evil-WORD 'evil-word))
        (count (or count 1)))
    (evil-signal-at-bob-or-eob count)
    (evil-forward-after-end thing count)))

(evil-define-motion evil-forward-after-WORD-end (count)
  "Move the cursor to the end of the COUNT-th next WORD."
  :type inclusive
  (evil-forward-after-word-end count t))

(map!
 :m "e" 'evil-forward-after-word-end
 :m "E" 'evil-forward-after-WORD-end
 :n "C-r"  nil
 :n "U" 'evil-undo)
#+end_src

** packages
*** vertico

#+begin_src elisp
(setq vertico-sort-function #'vertico-sort-history-alpha)
#+end_src

*** isearch

#+begin_src elisp
(define-key isearch-mode-map (kbd "M-j") 'avy-isearch)

(defun isearch-forward-other-window (prefix)
    "Function to isearch-forward in other-window."
    (interactive "P")
    (unless (one-window-p)
      (save-excursion
        (let ((next (if prefix -1 1)))
          (other-window next)
          (isearch-forward)
          (other-window (- next))))))

(defun isearch-backward-other-window (prefix)
  "Function to isearch-backward in other-window."
  (interactive "P")
  (unless (one-window-p)
    (save-excursion
      (let ((next (if prefix 1 -1)))
        (other-window next)
        (isearch-backward)
        (other-window (- next))))))

(define-key global-map (kbd "C-r") 'isearch-backward)
(define-key global-map (kbd "C-M-s") 'isearch-forward-other-window)
(define-key global-map (kbd "C-M-r") 'isearch-backward-other-window)
(define-key global-map (kbd "M-s-s") 'isearch-forward-regexp)
(define-key global-map (kbd "M-s-r") 'isearch-backward-regexp)
#+end_src

*** avy

[[https://karthinks.com/software/avy-can-do-anything/][Avy can do anything | Karthinks]]

Flipping gss and gs/

#+begin_src elisp
(map!
 (:map 'override
   :nvm "gss" #'evil-avy-goto-char-timer
   :nvm "gs/" #'evil-avy-goto-char-2))
#+end_src


#+begin_src elisp
(use-package! avy
 :config
 (setq avy-all-windows t)
)

(defun avy-action-embark (pt)
  (unwind-protect
      (save-excursion
        (goto-char pt)
        (embark-act))
    (select-window
     (cdr (ring-ref avy-ring 0))))
  t)

(setf (alist-get ?. avy-dispatch-alist) 'avy-action-embark)
#+end_src

*** ace-window

#+begin_src elisp
(map!
   :leader "w w" #'ace-window)
#+end_src

*** consult

#+begin_src elisp
(map!
   :leader "s f" #'consult-find
   :leader :desc "consult-outline" "s o" #'consult-outline
   :leader "b o" #'consult-buffer-other-window
   :leader "s y" #'consult-yank-from-kill-ring
   :leader "r l" #'consult-register-load
   :leader "r s" #'consult-register-store
   :leader "r r" #'consult-register
   [remap jump-to-register] #'consult-register-load)
#+end_src

*** spell-fu

[[https://github.com/doomemacs/doomemacs/issues/6246][doomemacs/doomemacs#6246 +spell/add-word does not create a personal dictionar...]]

#+begin_src sh :tangle no
mkdir -p ~/.config/emacs/.local/etc/ispell && echo personal_ws-1.1 en 0 >> ~/.config/emacs/.local/etc/ispell/.pws
#+end_src

Turn off spell-fu by default. If you remove the hook after! spell-fu, it's too late. spell-fu-ignore-modes only works if spell-fu-global-mode is set.

#+begin_src elisp
(remove-hook 'text-mode-hook #'spell-fu-mode)
;;(setq spell-fu-ignore-modes (list 'org-mode))
#+end_src

*** orderless

#+begin_src elisp
(use-package orderless
  :init
  (setq completion-styles '(orderless)
        completion-category-defaults nil
        completion-category-overrides '((file (styles . (partial-completion))))))
#+end_src

*** erc

message type codes: https://datatracker.ietf.org/doc/html/rfc2812

  #+begin_src elisp
  (setq erc-autojoin-channels-alist '(("libera.chat" "#haskell" "#emacs")))
  (setq erc-hide-list '("JOIN" "PART" "QUIT"))
  (setq erc-hide-timestamps t)
  (setq erc-autojoin-timing 'ident)
  ;; (erc-prompt-for-nickserv-password nil)
  (setq erc-track-exclude-types '("JOIN" "NICK" "PART" "QUIT" "MODE"
                                "324" "329" "332" "333" "353" "477"))
  #+end_src

*** latex

#+begin_src elisp
(after! latex
 (setq org-latex-packages-alist '(("" "tikz-cd" t) ("" "tikz" t)))
)
#+end_src

*** flycheck

#+begin_src elisp
(after! flycheck
  (map!
    :n "M-n" 'flycheck-next-error
    :n "M-p" 'flycheck-previous-error))
#+end_src

*** Next eglot

- [ ] check if working now ...
- [ ] reversal of tweak

#+begin_src elisp
(after! eglot
  (setq-default eglot-workspace-configuration
                '((haskell
                   (plugin
                    (stan
                     (globalOn . :json-false))))))  ;; disable stan
  (setq eglot-autoshutdown t)  ;; shutdown language server after closing last file
  (setq eglot-confirm-server-initiated-edits nil)  ;; allow edits without confirmation
  (push  '(haskell-ng-mode . ("haskell-language-server-wrapper" "--lsp")) eglot-server-programs))

(defun eldoc-documentation-tweak ()
    (interactive)
    (setq-local eldoc-echo-area-prefer-doc-buffer t
                eldoc-echo-area-use-multiline-p nil
                eldoc-documentation-strategy 'eldoc-documentation-enthusiast)
    (setq-local eldoc-documentation-functions
      '(flymake-eldoc-function
        eglot-signature-eldoc-function
        eglot-hover-eldoc-function)))
#+end_src

#+RESULTS:

* Org
** general tweaks

#+begin_src elisp
(after! org
  :config
  (setq
   org-log-into-drawer t
   org-startup-folded t
   org-support-shift-select t
   org-insert-heading-respect-content t
   org-startup-with-inline-images t
   org-cycle-include-plain-lists 'integrate
   ;; https://github.com/syl20bnr/spacemacs/issues/13465
   org-src-tab-acts-natively nil
   ;; from org-modern example
   org-auto-align-tags nil
   org-tags-column 0
   org-fold-catch-invisible-edits 'show-and-error
   org-special-ctrl-a/e t
   org-hide-emphasis-markers t
   org-pretty-entities t
   org-ellipsis "…"
   org-agenda-tags-column 0
   org-agenda-block-separator ?─)
   (remove-hook 'org-mode-hook 'flyspell-mode)
   (setq-default org-todo-keywords '((sequence "ToDo(t)" "Next(n)" "Blocked(b)" "|" "Done(d)")))
)
 #+end_src

** org-agenda

#+begin_src elisp
(after! org-agenda
  :config
  (setq org-agenda-span 'week
        org-agenda-use-time-grid nil
        org-agenda-start-day "-0d"
        org-agenda-block-separator nil
        org-agenda-skip-scheduled-if-done t
        org-agenda-inhibit-startup nil
        org-agenda-show-future-repeats nil
        org-agenda-compact-blocks t
        org-agenda-window-setup 'other-window
        org-agenda-show-all-dates nil
        org-agenda-prefix-format
         '((agenda . " %-24t")
           (todo . " %-24(org-name-short)")))
  (setq org-agenda-custom-commands
         '(("n" "next"
            ((agenda "" ((org-agenda-overriding-header "")))
             (todo "Next" ((org-agenda-overriding-header "Next")))))
           ("z" "z-agenda"
            ((agenda "" ((org-agenda-overriding-header "")))
             (todo "Next" ((org-agenda-overriding-header "Next")))
             (todo "Blocked" ((org-agenda-overriding-header "Blocked")))
             (todo "ToDo" ((org-agenda-overriding-header "ToDo")))))))
  (map! :leader "oz" #'agenda-z))

(defun org-name-short ()
  (interactive)
  (let
      ((xs (seq-subseq (file-name-split (buffer-file-name)) -2)))
      (concat
      (concat (nth 0 xs) "/")
      (file-name-base
      (nth 1 xs)))))

(defun agenda-z ()
  (interactive)
  (org-agenda nil "z"))
#+end_src

** org-capture

#+begin_src elisp
(after! org
  (setq
   org-capture-templates
   (quote
    (("r" "refile" entry
      (file "~/org/refile.org")
      "* ToDo %?
")
     ("z" "bugz" entry
      (file+headline "~/org/bugz.org" "bugz!")
      "* ToDo %?
%a")))))
#+end_src

** Turn company mode off

#+begin_src elisp
(after! org
  :config
  (progn
    (set-company-backend! 'org-mode nil)
    (set-company-backend! 'org-mode '(:separate company-yasnippet company-dabbrev))))
#+end_src

** yank-into-block

#+begin_src elisp
(after! org
  :config
  (defun display-ansi-colors ()
    (interactive)
    (let ((inhibit-read-only t))
      (ansi-color-apply-on-region (point-min) (point-max))))
   (add-hook 'org-babel-after-execute-hook #'display-ansi-colors)

   (map! :map org-mode-map
         :localleader
         (:prefix ("z" . "yank to block")
          :nvm "b" #'org-yank-into-new-block
          :nvm "e" #'org-yank-into-new-block-elisp
          :nvm "s" #'org-yank-into-new-block-sh
          :nvm "h" #'org-yank-into-new-block-haskell
          :nvm "n" #'org-new-block-haskell
          :nvm "z" (cmd! (org-new-block ""))
          :nvm "q" #'org-yank-into-new-quote)))

(defun org-yank-into-new-block (&optional template)
    (interactive)
    (let ((begin (point))
          done)
      (unwind-protect
          (progn
            (end-of-line)
            (yank)
            (push-mark begin)
            (setq mark-active t)
            (if template
             (org-insert-structure-template template)
             (call-interactively #'org-insert-structure-template))
            (setq done t)
            (deactivate-mark)
            (let ((case-fold-search t))
              (re-search-forward (rx bol "#+END_")))
            (forward-line 1))
        (unless done
          (deactivate-mark)
          (delete-region begin (point))))))

(defun org-new-block (&optional template)
    (interactive)
    (let ((begin (point))
          done)
      (unwind-protect
          (progn
            (end-of-line)
            (push-mark begin)
            (setq mark-active t)
            (if template
             (org-insert-structure-template template)
             (call-interactively #'org-insert-structure-template))
            (setq done t)
            (deactivate-mark)
            (evil-org-open-above 1))
        (unless done
          (deactivate-mark)
          (delete-region begin (point))))))

(defun org-yank-into-new-block-elisp ()
  (interactive)
  (org-yank-into-new-block "src elisp"))

(defun org-yank-into-new-block-sh ()
  (interactive)
  (org-yank-into-new-block "src sh :results output"))

(defun org-yank-into-new-block-haskell ()
  (interactive)
  (org-yank-into-new-block "src haskell-ng :results output"))

(defun org-new-block-haskell ()
  (interactive)
  (org-new-block "src haskell-ng :results output"))

(defun org-yank-into-new-quote ()
  (interactive)
  (org-yank-into-new-block "quote"))
#+end_src

** org-random-todo

[[https://github.com/unhammer/org-random-todo][unhammer/org-random-todo]]

#+begin_src elisp
(after! org
  (use-package! org-random-todo
    :defer-incrementally t
    :commands (org-random-todo-goto-new)
    :config
    (map! :map org-mode-map
        :localleader
        (:nvm "j" #'org-random-todo-goto-new))))

(after! org-agenda
  (map! :map org-agenda-mode-map
        :localleader
        (:nvm "j" #'org-random-todo-goto-new)))
#+end_src

** hugo

docs: [[https://ox-hugo.scripter.co/][ox-hugo - Org to Hugo exporter]]

~backtrace~ bug:
https://github.com/hlissner/doom-emacs/issues/5721#issuecomment-958342837

Setup is section-based. To add a post:

- add export_file_name to the properties.
#+begin_quote
:PROPERTIES:
:EXPORT_FILE_NAME: test2
:END:
#+end_quote

- add auto save at the bottom of the file:

  #+begin_quote
 * Locals

# Local Variables:
# eval: (org-hugo-auto-export-mode)
# End:
#+end_quote

A ToDo in the header makes the post a draft.

#+begin_src elisp
(after! org
  :config
  (use-package backtrace)
  (setq org-hugo-base-dir "~/site"
        org-hugo-auto-set-lastmod t
        org-hugo-use-code-for-kbd t
        org-hugo-date-format "%Y-%m-%d")
    (map! :map org-mode-map
        :localleader
        (:nvm "lp" #'org-hugo-export-wim-to-md)))
#+end_src

* haskell-ng

[[https://gitlab.com/magus/mes][Magnus Therning / My Emacs Setup · GitLab]]

** treesit installation (run first-time only)

I performed these steps manually, and this is indicative only:

  #+begin_src elisp :tangle no
  (add-to-list 'treesit-language-source-alist '(haskell "https://github.com/tree-sitter/tree-sitter-haskell"))
  (add-to-list 'treesit-language-source-alist '(cabal ("https://gitlab.com/magus/tree-sitter-cabal.git" "main" "src" "gcc-13" "c++-13")))
  (treesit-install-language-grammar 'haskell)
  (treesit-install-language-grammar 'cabal)
  #+end_src

** haskell-ng-mode

[[https://gitlab.com/magus/haskell-ng-mode][Magnus Therning / haskell-ng-mode · GitLab]]

#+begin_src elisp
(after! treesit
(use-package! haskell-ng-mode
  :diminish
  :load-path "~/.config/doom/repos/haskell-ng-mode"
  :init
  (add-to-list 'treesit-language-source-alist '(haskell "https://github.com/tree-sitter/tree-sitter-haskell"))
  ; (add-to-list 'treesit-language-source-alist '(cabal ("https://gitlab.com/magus/tree-sitter-cabal.git" "main" "src" "gcc-13" "c++-13")))
  (add-to-list 'treesit-language-source-alist '(cabal ("https://gitlab.com/magus/tree-sitter-cabal.git")))
  (add-to-list 'major-mode-remap-alist '(haskell-mode . haskell-ng-mode))
  (add-to-list 'major-mode-remap-alist '(cabal-mode . cabal-ng-mode))
  (defalias 'haskell-mode #'haskell-ng-mode)
  (defalias 'cabal-mode #'cabal-ng-mode)
  :hook
  ;;(haskell-ng-mode . eglot-ensure)
  (haskell-ng-mode . eldoc-documentation-tweak)
  (haskell-ng-mode . (lambda () (setq-local tab-width 2)))
  :config
  (use-package! ormolu)
  (map! :localleader
        :map haskell-ng-mode-map
        :nvm "'" #'haskell-ng-repl-run
        (:prefix ("=" . "format")
         :nvm "=" #'ormolu-format-buffer)
        (:prefix ("c" . "code")
         :nvm "a" #'eglot-code-actions)
        (:prefix ("," . "backend")
         :nvm "e" #'eglot
         :nvm "l" #'lsp
         :nvm "d" #'eldoc-documentation-tweak
         :nvm "r" #'eglot-reconnect
         :nvm "q" #'eglot-shutdown))
  (map! :localleader
        :map cabal-ng-mode-map
        (:prefix ("=" . "format")
         :nvm "=" #'cabal-format-buffer
         :nvm "r" #'cabal-format-region))))
#+end_src

** require

FIXME: Not sure why this is required

#+begin_src elisp
(require 'haskell-ng-mode)
#+end_src

#+RESULTS:
: haskell-ng-mode

** ob-haskell-ng

[[https://github.com/tonyday567/ob-haskell-ng][tonyday567/ob-haskell-ng]]

#+begin_src elisp
(use-package! ob-haskell-ng
  :load-path "~/.config/doom/repos/ob-haskell-ng"
  :config
  (setq org-babel-default-header-args '((:results . "replace output") (:exports . "both")))
)
#+end_src

** combobulate

[[https://github.com/mickeynp/combobulate][mickeynp/combobulate]]

 #+begin_src elisp
 (use-package! combobulate)
 #+end_src

** lsp-haskell (off)

#+begin_src elisp
(use-package! lsp-haskell
  :config
  (setq
        lsp-haskell-brittany-on nil
        lsp-haskell-floskell-on nil
        lsp-haskell-fourmolu-on nil
        lsp-haskell-stylish-haskell-on nil
        lsp-haskell-retrie-on nil
        lsp-haskell-plugin-import-lens-code-actions-on nil
        lsp-haskell-plugin-ghcide-type-lenses-config-mode nil
        lsp-haskell-plugin-ghcide-type-lenses-global-on nil
        lsp-haskell-plugin-import-lens-code-lens-on nil))
#+end_src

** treesit

#+begin_src elisp

(after! treesit
(defun ts-inspect ()
  (interactive)
  (when-let* ((nap (treesit-node-at (point))))
    (message "%S - %S" nap (treesit-node-type nap))))

(defun ts-query-root (query)
  (interactive "sQuery: ")
  (let ((ss0 (treesit-query-capture (treesit-buffer-root-node) query)))
    (message "%S" ss0))))

#+end_src

** flymake

#+begin_src elisp
(after! haskell-ng-mode
  (map! :localleader
        :map haskell-ng-mode-map
        "n" #'flymake-goto-next-error
        "p" #'flymake-goto-prev-error
        "e" #'consult-flymake))
#+end_src

** haskell-lite

[[https://github.com/tonyday567/haskell-lite][tonyday567/haskell-lite]]

#+begin_src elisp
(use-package! haskell-lite
  :load-path "~/.config/doom/repos/haskell-lite"
)
#+end_src

*** org-babel bindings

  #+begin_src elisp
  (after! org
  (map! :localleader
        :map org-mode-map
        (:prefix ("m" . "haskell-ng-repl")
         :nvm "s" #'haskell-ng-repl-run
         :nvm "p" #'haskell-lite-prompt
         :nvm :desc "run n go" "g" (cmd! (haskell-ng-repl-run t))
         :nvm "q" #'haskell-lite-repl-quit
         :nvm "r" #'haskell-lite-repl-restart
         :nvm "b" #'haskell-lite-repl-show)))
  #+end_src
*** haskell-ng-repl bindings

  #+begin_src elisp
  (after! org
  (map! :localleader
        :map haskell-ng-mode-map
        (:prefix ("m" . "haskell-ng-repl")
         :nvm "s" #'haskell-ng-repl-run
         :nvm "p" #'haskell-lite-prompt
         :nvm :desc "run n go" "g" (cmd! (haskell-ng-repl-run t))
         :nvm "q" #'haskell-lite-repl-quit
         :nvm "r" #'haskell-lite-repl-restart
         :nvm "b" #'haskell-lite-repl-show)))
  #+end_src
** Tidal

[[https://github.com/tidalcycles/Tidal][tidalcycles/Tidal: Pattern language]]

#+begin_src elisp
(use-package! tidal
    :init
    (progn
      (setq tidal-interpreter "ghci")
      (setq tidal-interpreter-arguments (list "ghci" "-XOverloadedStrings" "-package" "tidal"))
      (setq tidal-boot-script-path "~/.config/emacs/.local/straight/repos/Tidal/BootTidal.hs")
      ))
#+end_src

* Non-standard packages
** beacon

[[https://github.com/Malabarba/beacon][Malabarba/beacon]]

#+begin_src elisp
(use-package! beacon
  :config (beacon-mode 1))
#+end_src

** iscroll

[[https://github.com/casouri/iscroll][casouri/iscroll]]

#+begin_src elisp
(use-package! iscroll
  :config (iscroll-mode 1))
#+end_src

** ToDo diminish

- [ ] diminish not working for haskell-ng-mode

#+begin_src elisp
(use-package! diminish
  :config
  (diminish 'haskell-ng-mode))
#+end_src

** ToDo minions

[[https://github.com/tarsius/minions][GitHub - tarsius/minions: A minor-mode menu for the mode line]]

#+begin_src elisp
(use-package! minions
  :config
)
#+end_src

** auto-activating-snippets

[[https://github.com/ymarco/auto-activating-snippets][ymarco/auto-activating-snippets]]

#+begin_src elisp
(use-package! aas
    :hook (org-mode . aas-activate-for-major-mode)
    :config
        (aas-set-snippets 'org-mode
            ;; expand unconditionally
            "-]" "- [ ] "
            ";ig" #'insert-register
            ";ro" ":results output"))
#+end_src

** graphviz

[[https://github.com/ppareit/graphviz-dot-mode][ppareit/graphviz-dot-mode]]

#+begin_src elisp
(use-package graphviz-dot-mode
  :config
  (setq graphviz-dot-indent-width 4))
  (setq graphviz-dot-preview-extension "svg")
#+end_src

** ToDo uiua

#+begin_src elisp
(use-package! uiua-ts-mode
  :mode "\\.ua\\'")
#+end_src

** spacious-padding


[[https://protesilaos.com/codelog/2023-06-03-emacs-spacious-padding/][Emacs: my new ‘spacious-padding’ package | Protesilaos Stavrou]]

#+begin_src elisp
(use-package! spacious-padding
  :config
    (spacious-padding-mode t)
)
#+end_src

** vertico-posframe

[[https://github.com/tumashu/vertico-posframe][tumashu/vertico-posframe]]

#+begin_src elisp
(use-package! vertico-posframe
  :config
    (vertico-posframe-mode t)
)
#+end_src

** dashboard

[[https://github.com/emacs-dashboard/emacs-dashboard][emacs-dashboard/emacs-dashboard]]

[[https://orgmode.org/manual/Matching-tags-and-properties.html][Matching tags and properties (The Org Manual)]]

#+begin_src elisp
(use-package dashboard
  :ensure t
  :config
    (setq dashboard-items
      '((recents  . 5)
        (agenda . 5)
        (projects . 5)
        (bookmarks . 5)))
    (setq dashboard-banner-logo-title "welcome, Sir, to Cyprus. -- Goats and Monkeys!")
    ;(setq dashboard-display-icons-p t)
    ;(setq dashboard-icon-type 'nerd-icons)
    (setq dashboard-set-navigator t)
    (setq dashboard-startup-banner nil)
    (setq dashboard-set-footer nil)
    (setq dashboard-filter-agenda-entry 'dashboard-no-filter-agenda)
    ;(setq dashboard-agenda-sort-strategy '(todo-state-up))
    (setq dashboard-item-names '(("Recent Files:" . "Recent:")
                                 ("Agenda for the coming week:" . "Next:")))
    (setq dashboard-match-agenda-entry "+TODO=\"Next\"|SCHEDULED<\"<now>\"")
    ;(setq dashboard-set-heading-icons t)
    ;(setq dashboard-set-file-icons t)
    (map! :leader "ox" #'dashboard-open)
    (dashboard-setup-startup-hook))
#+end_src

** ToDo ef-themes

#+begin_src elisp
(use-package! ef-themes
  :config
  (setq ef-themes-to-toggle '(ef-bio ef-dark))
  (mapc #'disable-theme custom-enabled-themes)
  (ef-themes-select 'ef-bio))
#+end_src
